name: Delete Older Releases
description: delete older releases of any repo
author: dev-drprasad

branding:
  color: red
  icon: delete

inputs:
  keep_latest:
    description: how many latest releases to keep
    required: true
  repo:
    description: repo name in the form of <owner>/<repoName>
    required: false

runs:
  using: "node12"
  main: "index.js"
